// <auto-generated />
using System;
using Kolokwium_APBD_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium_APBD_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            BirthDate = new DateTime(2026, 6, 21, 19, 44, 1, 945, DateTimeKind.Local).AddTicks(8070),
                            FirstName = "Ania",
                            LastName = "Kowalska"
                        },
                        new
                        {
                            CustomerId = 2,
                            BirthDate = new DateTime(2026, 6, 21, 19, 44, 1, 952, DateTimeKind.Local).AddTicks(6530),
                            FirstName = "Patrycja",
                            LastName = "Nowak"
                        },
                        new
                        {
                            CustomerId = 3,
                            BirthDate = new DateTime(2026, 6, 21, 19, 44, 1, 952, DateTimeKind.Local).AddTicks(6550),
                            FirstName = "Maja",
                            LastName = "Kobierska"
                        });
                });

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeliveryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.ToTable("Delivery", (string)null);

                    b.HasData(
                        new
                        {
                            DeliveryId = 1,
                            CustomerId = 1,
                            Date = new DateTime(2026, 6, 21, 19, 44, 1, 955, DateTimeKind.Local).AddTicks(4180),
                            DriverId = 1
                        },
                        new
                        {
                            DeliveryId = 2,
                            CustomerId = 2,
                            Date = new DateTime(2026, 6, 21, 19, 44, 1, 955, DateTimeKind.Local).AddTicks(4420),
                            DriverId = 2
                        },
                        new
                        {
                            DeliveryId = 3,
                            CustomerId = 3,
                            Date = new DateTime(2026, 6, 21, 19, 44, 1, 955, DateTimeKind.Local).AddTicks(4430),
                            DriverId = 3
                        });
                });

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.HasKey("DriverId");

                    b.ToTable("Driver", (string)null);

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            LicenceNumber = "123456789"
                        },
                        new
                        {
                            DriverId = 2,
                            FirstName = "John",
                            LastName = "Nowak",
                            LicenceNumber = "123456788"
                        },
                        new
                        {
                            DriverId = 3,
                            FirstName = "Wiktor",
                            LastName = "Kobierski",
                            LicenceNumber = "123456787"
                        });
                });

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Produkt 1",
                            Price = 10f
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Produkt 2",
                            Price = 20f
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Produkt 3",
                            Price = 30f
                        });
                });

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.ProductDelivery", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "DeliveryId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("ProductDelivery", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DeliveryId = 1,
                            Amount = 1
                        },
                        new
                        {
                            ProductId = 2,
                            DeliveryId = 2,
                            Amount = 2
                        },
                        new
                        {
                            ProductId = 3,
                            DeliveryId = 3,
                            Amount = 3
                        });
                });

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.Delivery", b =>
                {
                    b.HasOne("Kolokwium_APBD_2.Entities.Customer", "Customer")
                        .WithMany("Deliveries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium_APBD_2.Entities.Driver", "Driver")
                        .WithMany("Deliveries")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.ProductDelivery", b =>
                {
                    b.HasOne("Kolokwium_APBD_2.Entities.Delivery", "Delivery")
                        .WithMany("ProductDeliveries")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium_APBD_2.Entities.Product", "Product")
                        .WithMany("ProductDeliveries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.Customer", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.Delivery", b =>
                {
                    b.Navigation("ProductDeliveries");
                });

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.Driver", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("Kolokwium_APBD_2.Entities.Product", b =>
                {
                    b.Navigation("ProductDeliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
